### ISSUE TITLE
RelativeTime is broken on PHP 8.1

### ISSUE THREAD

**Issue by grkb-chaziz** [mpratt/RelativeTime#14]
![image](https://user-images.githubusercontent.com/88458384/149581577-33886809-ed1e-4a63-82fb-d50f794c598f.png)

Return type of RelativeTime\Languages\LanguageAdapter::offsetExists($id) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\xampp_NEW\cheeserox\vendor\mpratt\relativetime\Lib\RelativeTime\Languages\LanguageAdapter.php on line 62

**Comment by mpratt** [comment]
Thanks for the report @bluey2000k 
I'll look into fixing this issue someday  around tuesday/wednesday

**Comment by grkb-chaziz** [comment]
I'm kind of worried the fix would most likely break support for versions prior to 8.1

**Comment by mpratt** [comment]
Dont worry @bluey2000k Im looking into changing the way translations work in order to maintain compatibility with older versions too. I'll be pushing the fix today or tomorrow.

**Comment by mpratt** [comment]
Could you take a look at the master branch and see if the library is working on your setup.
I'll be tagging/releasing a new version tomorrow probably

**Comment by mpratt** [comment]
Tagged new version 1.5.10. It should work with 8.1 and older.
