### ISSUE TITLE
Correct way to override offsets in 1.5.10?

### ISSUE THREAD

**Issue by ThomWilhelm** [mpratt/RelativeTime#15]
Hi there, firstly thank you for this package! I find it really useful!

I noticed in this commit https://github.com/mpratt/RelativeTime/commit/c5b4cdbe063ca422389354f75134c4bd13334678#diff-df7bfda02362f522c4bb78cbf4329fe4af9d65e37ecda9157f07d3eac79de0df

The method offsetSet was removed, which I previously used in my project to change the default "just now" to something more friendly like "About to end...". This means code I had before doesn't work anymore.

```
$english = new English();
$english->offsetSet('now', "About to end...");
```

I guess I could create my own class with my custom strings, is that the best way to overrides certain strings now?

**Comment by mpratt** [comment]
Hallo @ThomWilhelm !
Thanks for the report. I pushed a new version 1.5.11, which has the `set(key, value)` method. It allows the same behavior as offsetSet. 

I think something like this, should work now.

```php
$english = new English();
$english->set('now', "About to end...");
```

I think it is useful to have a method like that for quick changes on translations.

**Comment by ThomWilhelm** [comment]
This is perfect thank you for the quick fix!
