### ISSUE TITLE
Plural translation of days in German slightly incorrect

### ISSUE THREAD

**Issue by sklerotraficon** [mpratt/RelativeTime#18]
I just noticed, that the plural of the days in German is slightly incorrect in the context of time "ago" in line: 
https://github.com/mpratt/RelativeTime/blob/976db7deed8efef2b5958947711eeabd2d616fea/Lib/RelativeTime/Languages/German.php#L37

It should be: 
`'plural' => '%d Tagen',`
(note the 'n' at the end)
as this results to "vor 5 Tagen", which linguistically correct.

**Comment by mpratt** [comment]
Vielen Dank für den Pull Request. Tut mir leid, dass ich so lange gebraucht habe, um ihn zu "mergen". Nochmals danke!
